services:
  db:
    image: postgres:latest
    container_name: postgres_flowe
    environment:
      POSTGRES_USER: flowe
      POSTGRES_PASSWORD: flowe
      POSTGRES_DB: flowe_dev
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flowe -d flowe_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local