spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/flowe_dev
    username: flowe
    password: flowe
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
springdoc:
  show-actuator: true